### ISSUE TITLE
Usage doesn't show --output-as optional argument

### ISSUE THREAD

**Issue by metadaddy** [robertbreker/cxcli#3]

**Comment by robertbreker** [comment]
Selecting the output format only is an option when within a service and command:

 `cx systemlog GetRecords -h
usage: cx systemlog GetRecords [-h] [--customer CUSTOMER] [--startDateTime STARTDATETIME] [--endDateTime ENDDATETIME] [--limit LIMIT]
                               [--continuationToken CONTINUATIONTOKEN] [--output-as {json,yaml,table,csv,rawprint} | --output-binary path_to_file]
                               [--cliquery CLIQUERY]

Gets Log Records With A Specified Query And Returns The Estimated Total Items Count

optional arguments:
  -h, --help            show this help message and exit
  --customer CUSTOMER   ID of the customer. (default: dvintfd45cca)
  --startDateTime STARTDATETIME
                        Start DateTime for the records to be retrieved.
  --endDateTime ENDDATETIME
                        End DateTime for the records to be retrieved.
  --limit LIMIT         How many items to be returned per page
  --continuationToken CONTINUATIONTOKEN
                        Continuation token for the next page.
  --output-as {json,yaml,table,csv,rawprint}
                        Try presenting the result in the specified format (default: JSON)
  --output-binary path_to_file
                        Store the result at the provided path
  --cliquery CLIQUERY   Filter the result using JMESPath (See https://jmespath.org/tutorial.html)`

The only alternative would be to always require specification before the service and command (like --verbose).

Any thoughts?

**Comment by metadaddy** [comment]
Ah - I had expected to see it in the response to a plain `cx -h`, but the way you have it makes sense.
